defmodule Projection.CompileProjectionCodegenTaskTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO
  import Projection.CodegenTestHelpers

  @required_ui_shell_files ~w(app_shell.slint error.slint screen.slint ui.slint)

  defmodule AliasRouteRouter do
    use Projection.Router.DSL

    alias Projection.TestScreens.Devices

    screen_session :main do
      screen("/monitoring", Devices, :index, as: :monitoring)
    end
  end

  setup do
    restore_ui_shell_files = ensure_required_ui_shell_files!()
    on_exit(restore_ui_shell_files)
    :ok
  end

  test "compile.projection_codegen completes without recursive loadpath failures" do
    cleanup =
      setup_codegen_env(
        router_module: :delete,
        screen_modules: [Projection.TestScreens.Clock],
        restore_codegen: false
      )

    on_exit(cleanup)

    capture_io(fn ->
      assert {:ok, []} = Mix.Tasks.Compile.ProjectionCodegen.run([])
    end)
  end

  test "projection.codegen raises when a screen declares unsupported :map fields" do
    module_name = :"MapFieldScreen#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :screen

      schema do
        field :data, :map, default: %{}
      end
    end
    """

    Code.compile_string(source)

    cleanup = setup_codegen_env(router_module: :delete, screen_modules: [module])
    on_exit(cleanup)

    assert_raise ArgumentError, ~r/does not support.*:map/, fn ->
      capture_io(fn ->
        Mix.Tasks.Projection.Codegen.run([])
      end)
    end
  end

  test "projection.codegen emits typed list bindings from schema items option" do
    module_name = :"TypedListScreen#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :screen

      schema do
        field :tiles, :list, items: :integer, default: [1, 2, 3]
        field :ratios, :list, items: :float, default: [1.0, 0.5]
        field :flags, :list, items: :bool, default: [true, false]
        field :labels, :list, default: ["a", "b"]
      end

      @impl true
      def render(assigns), do: assigns
    end
    """

    Code.compile_string(source)

    cleanup = setup_codegen_env(router_module: :delete, screen_modules: [module])
    on_exit(cleanup)

    capture_io(fn ->
      Mix.Tasks.Projection.Codegen.run([])
    end)

    screen_name =
      module
      |> Module.split()
      |> List.last()
      |> Macro.underscore()

    state_slint = File.read!("slint/ui_host/src/generated/#{screen_name}_state.slint")
    refute state_slint =~ "import {", "no id_table structs => no types import in state file"

    types_only =
      File.read!("slint/ui_host/src/generated/#{screen_name}_types.slint")

    assert types_only =~ "generated by mix projection.codegen"
    refute types_only =~ "export struct"

    assert state_slint =~ "in property <[int]> tiles: [1, 2, 3];"
    assert state_slint =~ ~r/in property <\[float\]> ratios: \[(1|1\.0), 0\.5\];/
    assert state_slint =~ "in property <[bool]> flags: [true, false];"
    assert state_slint =~ "in property <[string]> labels: [\"a\", \"b\"];"

    screen_rs = File.read!("slint/ui_host/src/generated/#{screen_name}.rs")

    assert screen_rs =~
             "fn parse_integer_list(value: &Value, path: &str) -> Result<Vec<i64>, String>"

    assert screen_rs =~
             "fn parse_float_list(value: &Value, path: &str) -> Result<Vec<f64>, String>"

    assert screen_rs =~
             "fn parse_bool_list(value: &Value, path: &str) -> Result<Vec<bool>, String>"

    assert screen_rs =~ "collect::<Result<Vec<i32>, String>>()?"
    assert screen_rs =~ "let model = slint::VecModel::from(parsed);"
  end

  test "projection.codegen emits struct-based id_table bindings" do
    module_name = :"TypedIdTableScreen#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :screen

      schema do
        field(:devices, :id_table,
          columns: [name: :string, pos: :integer, load: :float, online: :bool],
          default: %{
            order: ["dev-1", "dev-2"],
            by_id: %{
              "dev-1" => %{name: "A", pos: 1, load: 0.5, online: true},
              "dev-2" => %{name: "B", pos: 2, load: 1.0, online: false}
            }
          }
        )
      end

      @impl true
      def render(assigns), do: assigns
    end
    """

    Code.compile_string(source)

    cleanup = setup_codegen_env(router_module: :delete, screen_modules: [module])
    on_exit(cleanup)

    capture_io(fn ->
      Mix.Tasks.Projection.Codegen.run([])
    end)

    screen_name =
      module
      |> Module.split()
      |> List.last()
      |> Macro.underscore()

    # Types file: struct definitions live in per-screen types file
    types_slint =
      File.read!("slint/ui_host/src/generated/#{screen_name}_types.slint")

    assert types_slint =~ "export struct DevicesRow {"
    assert types_slint =~ "id: string,"
    assert types_slint =~ "name: string,"
    assert types_slint =~ "pos: int,"
    assert types_slint =~ "load: float,"
    assert types_slint =~ "online: bool,"

    # State file: imports from per-screen types file (Slint include path, not ui_root-relative)
    state_slint = File.read!("slint/ui_host/src/generated/#{screen_name}_state.slint")
    assert state_slint =~ ~s(import { DevicesRow } from "#{screen_name}_types.slint";)
    assert state_slint =~ "in property <[DevicesRow]> devices: [];"

    refute File.exists?(Path.join(configured_ui_root(), "types.slint")),
           "monolithic types.slint should not be emitted (per-screen types/ instead)"

    # No parallel arrays
    refute state_slint =~ "devices_ids"
    refute state_slint =~ "devices_name"

    # Rust: struct-based construction from parsed id_table
    screen_rs = File.read!("slint/ui_host/src/generated/#{screen_name}.rs")
    assert screen_rs =~ "parse_id_table(value, path)"
    assert screen_rs =~ "crate::DevicesRow {"
    assert screen_rs =~ "id: id.clone().into(),"
    assert screen_rs =~ ~s[parsed.columns.get("name")]
    assert screen_rs =~ ~s[parsed.columns.get("pos")]
    assert screen_rs =~ ~s[parsed.columns.get("load")]
    assert screen_rs =~ ~s[parsed.columns.get("online")]
  end

  test "projection.codegen emits multiple structs for multiple id_tables" do
    module_name = :"MultiIdTableScreen#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :screen

      schema do
        field(:devices, :id_table,
          columns: [name: :string, status: :string],
          default: %{order: [], by_id: %{}}
        )
        field(:sensors, :id_table,
          columns: [label: :string, value: :float],
          default: %{order: [], by_id: %{}}
        )
      end

      @impl true
      def render(assigns), do: assigns
    end
    """

    Code.compile_string(source)

    cleanup = setup_codegen_env(router_module: :delete, screen_modules: [module])
    on_exit(cleanup)

    capture_io(fn ->
      Mix.Tasks.Projection.Codegen.run([])
    end)

    screen_name =
      module
      |> Module.split()
      |> List.last()
      |> Macro.underscore()

    types_slint =
      File.read!("slint/ui_host/src/generated/#{screen_name}_types.slint")

    assert types_slint =~ "export struct DevicesRow {"
    assert types_slint =~ "export struct SensorsRow {"

    state_slint = File.read!("slint/ui_host/src/generated/#{screen_name}_state.slint")
    assert state_slint =~ ~s(import { DevicesRow, SensorsRow } from "#{screen_name}_types.slint";)
    assert state_slint =~ "in property <[DevicesRow]> devices: [];"
    assert state_slint =~ "in property <[SensorsRow]> sensors: [];"

    screen_rs = File.read!("slint/ui_host/src/generated/#{screen_name}.rs")
    assert screen_rs =~ "crate::DevicesRow {"
    assert screen_rs =~ "crate::SensorsRow {"
  end

  test "projection.codegen emits minimal types file for non-id_table screens and build.rs include path" do
    cleanup =
      setup_codegen_env(router_module: :delete, screen_modules: [Projection.TestScreens.Clock])

    on_exit(cleanup)

    capture_io(fn ->
      Mix.Tasks.Projection.Codegen.run([])
    end)

    types_path = "slint/ui_host/src/generated/clock_types.slint"
    assert File.exists?(types_path)

    types_slint = File.read!(types_path)
    assert types_slint =~ "generated by mix projection.codegen"
    refute types_slint =~ "export struct"

    state_slint = File.read!("slint/ui_host/src/generated/clock_state.slint")
    refute state_slint =~ "import {"

    build_rs = File.read!("slint/ui_host/build.rs")
    assert build_rs =~ "compile_with_config"
    assert build_rs =~ "CompilerConfiguration"
    assert build_rs =~ ~S|with_include_paths(vec!["src/generated".into()])|
  end

  test "projection.codegen maps aliased route names to the referenced screen id" do
    cleanup =
      setup_codegen_env(router_module: AliasRouteRouter, screen_modules: :delete)

    on_exit(cleanup)

    capture_io(fn ->
      Mix.Tasks.Projection.Codegen.run([])
    end)

    mod_rs = File.read!("slint/ui_host/src/generated/mod.rs")

    assert mod_rs =~ "Some(\"monitoring\") => ScreenId::Devices"
    refute mod_rs =~ "Some(\"devices\") => ScreenId::Devices"
  end

  test "compile.projection_codegen retries after failure on next run" do
    module_name = :"RetryScreen#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :screen

      schema do
        field :data, :map, default: %{}
      end
    end
    """

    Code.compile_string(source)

    cleanup =
      setup_codegen_env(
        router_module: :delete,
        screen_modules: [module],
        restore_codegen: false
      )

    on_exit(cleanup)

    # First run fails due to unsupported :map field
    capture_io(fn ->
      assert {:error, [message]} = Mix.Tasks.Compile.ProjectionCodegen.run([])
      assert message =~ "projection_codegen failed"
    end)

    # Fix the env so next run succeeds
    Application.put_env(:projection, :screen_modules, [Projection.TestScreens.Clock])
    Mix.Task.reenable("projection.codegen")

    capture_io(fn ->
      assert {:ok, []} = Mix.Tasks.Compile.ProjectionCodegen.run([])
    end)
  end

  test "projection.codegen rejects unsupported field types in app_state" do
    module_name = :"BadAppState#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :app_state

      schema do
        field :data, :map, default: %{}
      end
    end
    """

    Code.compile_string(source)

    original_app_module = Application.get_env(:projection, :app_module)
    Application.put_env(:projection, :app_module, module)

    cleanup = setup_codegen_env(screen_modules: [Projection.TestScreens.Clock])

    on_exit(fn ->
      if is_nil(original_app_module) do
        Application.delete_env(:projection, :app_module)
      else
        Application.put_env(:projection, :app_module, original_app_module)
      end

      cleanup.()
    end)

    assert_raise Mix.Error, ~r/does not support.*:map.*app_state/, fn ->
      capture_io(fn ->
        Mix.Tasks.Projection.Codegen.run([])
      end)
    end
  end

  test "projection.codegen catches render/1 key mismatches at build time" do
    module_name = :"BadRenderScreen#{System.unique_integer([:positive])}"
    module = Module.concat([Projection, module_name])

    source = """
    defmodule #{inspect(module)} do
      use ProjectionUI, :screen

      schema do
        field :title, :string, default: "hello"
      end

      @impl true
      def render(_assigns), do: %{wrong_key: "oops"}
    end
    """

    Code.compile_string(source)

    cleanup = setup_codegen_env(router_module: :delete, screen_modules: [module])
    on_exit(cleanup)

    assert_raise ArgumentError, ~r/do not match schema keys/, fn ->
      capture_io(fn ->
        Mix.Tasks.Projection.Codegen.run([])
      end)
    end
  end

  defp ensure_required_ui_shell_files! do
    ui_root = Path.join(File.cwd!(), configured_ui_root())
    File.mkdir_p!(ui_root)

    snapshots =
      Map.new(@required_ui_shell_files, fn file ->
        path = Path.join(ui_root, file)

        snapshot =
          case File.read(path) do
            {:ok, content} -> {:existing, content}
            {:error, _reason} -> :missing
          end

        {file, snapshot}
      end)

    Enum.each(@required_ui_shell_files, fn file ->
      path = Path.join(ui_root, file)

      if Map.fetch!(snapshots, file) == :missing do
        File.write!(path, "// required by projection.codegen tests\n")
      end
    end)

    fn ->
      Enum.each(@required_ui_shell_files, fn file ->
        path = Path.join(ui_root, file)

        case Map.fetch!(snapshots, file) do
          {:existing, content} ->
            File.write!(path, content)

          :missing ->
            File.rm(path)
        end
      end)

      case File.ls(ui_root) do
        {:ok, []} -> File.rmdir(ui_root)
        _ -> :ok
      end
    end
  end

  defp configured_ui_root do
    case Application.get_env(:projection, :ui_root) do
      path when is_binary(path) and path != "" ->
        path

      _ ->
        app =
          case Mix.Project.config()[:app] do
            value when is_atom(value) -> Atom.to_string(value)
            _ -> "projection"
          end

        Path.join(["lib", app, "ui"])
    end
  end
end
